<?php
/**
 * Simple empty layout for rendering html parts with ajax
 */
?>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= $this->css('bootstrap/css/bootstrap.min.css') ?>
    <?= $this->css('css/style.css') ?>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
   

    <?= $this->title() ?>
    <?= $this->description() ?>

    <?= \isv\View\SeoHelper::author('isvteam.com') ?>
</head>
<body>
   
    <div class="flash"> 
            <?php if (\isv\IS::app()->session()->flash('success')) : ?>
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?= \isv\IS::app()->session()->getFlash("success") ?>
                </div>
            <?php endif; ?>
            <?php if (\isv\IS::app()->session()->flash('error')) : ?>
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <?= \isv\IS::app()->session()->getFlash("error") ?>
                </div>
            <?php endif; ?>
        </div>
    
<?=$this->content()?>
    
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <?= $this->js('bootstrap/js/bootstrap.min.js') ?>
     <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <?= $this->js('js/main.js') ?>
</body>


