<h1>Формирование имени</h1>

<div class="col-sm-12">
    <div class="col-sm-6">
        <form method="post">

            <?php if ($cat) : ?>
                <?php foreach ($cat as $k => $v) : ?>
                    <div class="form-group">

                        <label><?= $v ?></label>
                        <input class="form-control" name="<?= $k ?>" value="<?= $convertName[$k] ? $convertName[$k] : '' ?>">

                    </div>
                <?php endforeach; ?>

                <div class="form-group">
                    <button class="btn btn-primary">Сохранить</button>
                </div>
            <?php endif; ?>

        </form>
    </div>
    <div class="col-sm-6">
        <h3>Переменные</h3>
        <?php if ($fields) : ?>
            <table class="table">
                <?php foreach ($fields as $k => $v) : ?>
                    <tr>
                        <td><?=$v?></td>
                        <td>{<?=$k?>}</td>
                    </tr>
                    <?php endforeach; ?>
                </table>
        <?php endif; ?>
    </div>
</div>