<h1>Авторизация на сайте <a href="http://b2b.euro-diski.ru/">b2b.euro-diski.ru</a></h1>


<?php if (\isv\IS::app()->component('main')->isAuth()) :?>
<span style="color: #337ab7; font-size: 50px;">Вы авторизированы!</span>
<a href="/settings/logout">
<button class="btn btn-primary">Выйти</button>
</a>
<?php else: ?>
<span style="color: red; font-size: 15px;">Вы не авторизированы!</span>

<form method="post">
    <div class="form-group">
        <label>Логин</label>
        <input name="login" value="<?=$log['login']?>">
    </div>
    <div class="form-group">
        <label>Пароль</label>
        <input name="password" value="<?=$log['password']?>">
    </div>
    <div class="form-group">
        <button class="btn btn-primary">Войти</button>
    </div>
</form>

<?php endif;?>




