<?php
/**
 * Created by PhpStorm.
 * User: vladimir
 * Date: 4/29/17
 * Time: 6:17 PM
 */
namespace Controller\BaseControllers;
use isv\Controller\ControllerBase;
use isv\IS;

/**
 * Class AdminController
 * @package Controller\BaseControllers
 */
class AdminController extends ControllerBase
{
    public function init()
    {
        IS::app()->set('title', 'ADMIN');
        if( IS::app()->get('action') !== 'loginAction')
        {
           if(!IS::app()->user()->isAuth() || (int)IS::app()->user()->id !== IS::app()->getConfig('config')['admin']){
                $this->redirect('/admin/login');exit(1);
            }
        }
        IS::app()->set('templateName', 'default');
        IS::app()->set('layout', 'default');
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        // TODO: Implement indexAction() method.
    }
}