<?php
namespace Models\Repositories;
use isv\DB\ModelBase;

/**
* class UserDataRepository Generated by ISV framework generator
* @version 1.1
* @package Models
*
*/
class UserDataRepository extends ModelBase
{
    /**
    *@param string $table
    */
    protected $table = 'userData';
    
    /**
    *@param mixed $id
    *type int(11)
    *@default 
    */
    protected $id;
    
    /**
    *@param mixed $userId
    *type int(11)
    *@default 
    */
    protected $userId;
    
    /**
    *@param mixed $label
    *type varchar(50)
    *@default 
    */
    protected $label;
    
    /**
    *@param mixed $val
    *type varchar(255)
    *@default 
    */
    protected $val;
    
    /**
     *
     * Get primary key 
     * @return  int
     */
    public function getPrimary()
    {
        return 'id';
    }
    
    /**
     *
     * Setter Function for userId
     * @param $userid
     * @return  $this
     */
    public function setUserId($userid)
    {
        $this->userId = $userid;
        return $this;
    }
    
    /**
     *
     * Setter Function for label
     * @param $label
     * @return  $this
     */
    public function setLabel($label)
    {
        $this->label = $label;
        return $this;
    }
    
    /**
     *
     * Setter Function for val
     * @param $val
     * @return  $this
     */
    public function setVal($val)
    {
        $this->val = $val;
        return $this;
    }
    
    /**
     *
     * getter Function for $id
     * @return  $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     *
     * getter Function for $userId
     * @return  $userId
     */
    public function getUserId()
    {
        return $this->userId;
    }
    
    /**
     *
     * getter Function for $label
     * @return  $label
     */
    public function getLabel()
    {
        return $this->label;
    }
    
    /**
     *
     * getter Function for $val
     * @return  $val
     */
    public function getVal()
    {
        return $this->val;
    }
    
    /**    *@return bool    */
    public function validateData(){ return true; }

    /**    *@return array    */
    public function forms(){ return parent::forms(); }
}
