<?php
/**
 * @var $id int
 * @var $name string
 */
?>

<div class="row col-md-3">
    <ul class="nav nav-pills nav-stacked">
        <li><a href="/isv">Model Generator</a></li>
        <li class="active"><a href="/isv/crud">Crud generator</a></li>
    </ul>
</div>

<div class="container col-md-9">
    <h2 class="text-center">Generate Model From database</h2>
    <form action="/isv/crud" method="post">
        <div class="form-group">
            <label>Extend class from \isv\Controller (ControllerBase AdminController)</label>
            <input type="text" name="EXTENDS_CLASS" class="form-control">
        </div>
        <div class="form-group">
            <label>Model namespace (Models\Admin or Models) </label>
            <input type="text" name="MODEL_NAMESPACE" class="form-control">
        </div>
        <div class="form-group">
            <label>Model name (ProductsModel) </label>
            <input type="text" name="MODEL_NAME" class="form-control">
        </div>

        <div class="form-group">
            <input type="hidden" name="CREATED" value="<?=date('d-m-y H:i:s')?>">
            <input type="submit" class="btn btn-primary" value="GO!" />
        </div>
    </form>
</div>