<?php
/**
 * @var $id int
 * @var $name string
 */
?>

<div class="row col-md-3">
    <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/isv">Model Generator</a></li>
        <li><a href="/isv/crud">Crud generator</a></li>
    </ul>
</div>

<div class="container col-md-9">
    <h2 class="text-center">Generate Model From database</h2>
    <form action="/isv/process" method="post">
        <div class="form-group">
            <label>Model</label>
            <input type="text" name="table" class="form-control">
        </div>
        <div class="form-group">
            <label for="model">
                Overwrite model
                <input type="checkbox" name="model" id="model" />
            </label>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="GO!" />
        </div>
    </form>
</div>