<h1>Удаление материалов</h1>

<div>
    <span style="font-size: 20px;">
        <strong>
            Категорий: <?=$q_categories?>, Товаров: <?=$q_products?>
        </strong>
    </span> 
    <a href="/view/del_pr"><button class="btn btn-danger">Очистить</button></a>
</div>

<div>
    <span style="font-size: 20px;">
        <strong>
           Изображений: <?=$q_img?>
        </strong>
    </span> 
    <a href="/view/del_img"><button class="btn btn-danger">Очистить</button></a>
</div>