<?php
namespace Models;
use Models\Repositories\UsersRepository;

/**
* class UsersModel Generated by ISV framework generator
* @version 1.1
* @package Models
*
*/
class UsersModel extends UsersRepository
{
    /**
    *Method forms define rules for generate forms from this model
    */
    public function forms()
    { 
        return [
            'id' => ['type' => 'number','name'=>'','val'=>$this->id,'table'=>false,'form'=>false,'search'=>false],
            
            'email' => ['type' => 'text','name'=>'','val'=>$this->email,'table'=>false,'form'=>false,'search'=>false],
            'username' => ['type' => 'text','name'=>'Логин','val'=>$this->username],
            'password' => ['type' => 'text','name'=>'Пароль','val'=>$this->password,'table'=>true,'search'=>false],
            'rememberToken' => ['type' => 'text','name'=>'','val'=>$this->rememberToken,'table'=>false,'form'=>false,'search'=>false],
            'registerDate' => ['type' => 'date','name'=>'Дата регистрации','val'=>$this->registerDate,'form'=>false],
            'lastLogin' => ['type' => 'date','name'=>'Последний вход','val'=>$this->lastLogin,'form'=>false],
            'ip' => ['type' => 'text','name'=>'IP','val'=>$this->ip,'form'=>false,'table'=>false,'search'=>false],
            'confirmed' => ['type' => 'checkbox','name'=>'','val'=>$this->confirmed,'table'=>false,'form'=>false,'search'=>false],
            'blocked' => ['type' => 'checkbox','name'=>'','val'=>$this->blocked,'table'=>false,'form'=>false,'search'=>false],
            'role' => ['type' => 'number','name'=>'Права доступа','table'=>false,'val'=>$this->role,'search'=>false],
            'role_convert' => ['type' => 'number','name'=>'Права доступа','val'=>$this->role,'form'=>false,'search'=>false],
            'shop' => ['type' => 'text','name'=>'Магазин','val'=>$this->shop,'search'=>false,'table'=>false],
            'shop_convert' => ['type' => 'text','name'=>'Магазин','val'=>$this->shop,'search'=>false,'form'=>false],
        ];
    }
    
    public function beforeSave() {
       // $this->role = (int)$this->role > 0 ? (int)$this->role : 2;
        return true;
    }

        public function getSelectFields(){
        return [
            'role'=>[
                'table'=>'roles',
                'relations'=>'code',
                'val'=>'name'
            ],
            'shop'=>[
                'table'=>'shops',
                'relations'=>'code',
                'val'=>'name'
            ],
            
        ];
    }
    
}
